bbonfhir-server-app/src/main/config/jetty-config.xml
As part of CCBF-28, had to get fix several problems that were found with the stripped-down Jetty config XML.
=> CBBF-28: FHIR Server deployment to HealthAPT AWS: Fix Jetty config

bbonfhir-server-app/pom.xml, bbonfhir-server-app/src/main/config/server-config-healthapt.sh
This PR contains the code changes required for http://issues.hhsdevcloud.us/browse/CBBI-139.
=> CBBI-139: Switch HealthAPT envs to deploy BB API webapp in Wildfly: dev

bbonfhir-server-app/src/main/java/ca/uhn/fhir/jpa/demo/JpaServerDemo.java
http://issues.hhsdevcloud.us/browse/CBBF-1
Pulling some additional changes from HAPI v2.0. Should have included these in the last PR, really.
=> CBBF-1: Making some additional configuration changes to match HAPI v2.0.

bbonfhir-server-app/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfig.java
http://issues.hhsdevcloud.us/browse/CBBF-39
=> CBBF-39: Actually remove Lucene indexes from HAPI FHIR server

bluebutton-server-app/pom.xml, pom.xml
Whoops: I'd forgotten to commit my version number change. Here it is.
=> CBBF-40: Clean up bbonfhir-server project (round 3)

README.md, bluebutton-server-app/pom.xml, bluebutton-server-app/src/main/config/server-config-healthapt.sh, bluebutton-server-app/src/main/config/server-config.sh, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/BlueButtonServer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/FhirServerConfig.java, bluebutton-server-app/src/main/resources/logback.xml, bluebutton-server-app/src/main/webapp/WEB-INF/web.xml, bluebutton-server-app/src/test/resources/logback-test.xml, pom.xml
These changes were all made back in November when I was trying to diagnose and resolve the ETL performance problems. Turns out that the primary root cause had nothing to do with the FHIR server -- it was actually the DB server. Nonetheless, many of the changes made were still good ideas.
=> CBBD-154 and CBBF-46 Performance work

bluebutton-server-app/pom.xml
http://issues.hhsdevcloud.us/browse/CBBF-48
=> CBBF-48: Updated to the latest PostgreSQL JDBC driver, to get PG 9.6 support.

bluebutton-server-app/pom.xml, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/FhirServerConfig.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/BlueButtonServerIT.java
http://issues.hhsdevcloud.us/browse/CBBF-47
Whoops! Had forgotten to push these changes into a PR. Can you review them, @dho937? (It's small.)
=> CBBF-47: Move to HAPI 2.2 and the latest FHIR structures (from 2016-12)

bluebutton-server-app/src/main/resources/logback.xml
http://issues.hhsdevcloud.us/browse/CBBF-51
=> CBBF-51: Makes the FHIR server's logging during ETL less noisy.

bluebutton-server-app/src/main/config/server-config-healthapt.sh
Just contains the changes that I made to this script as part of http://issues.hhsdevcloud.us/browse/CBBI-181. Had to fix a number of little things to get it working again.
=> CBBI-181: Updates to JBoss/Wildfly configuration and deploy script

bluebutton-server-app/src/main/config/server-config-healthapt.sh
http://issues.hhsdevcloud.us/browse/CBBF-52
=> CBBF-52: Fixed the default logging path: don't write to a hidden file, silly.

bluebutton-server-app/src/main/config/server-config-healthapt.sh
http://issues.hhsdevcloud.us/browse/CBBF-57
=> CBBF-57: Fixed the default management port

bluebutton-server-app/pom.xml, pom.xml
The real fix here is the MVCC configuration in the connection URL. I
just bumped the HSQL version because, why not?
http://issues.hhsdevcloud.us/browse/CBBF-58
=> CBBF-58: Configure HSQL such that it can handle large amounts of data

bluebutton-server-app/pom.xml, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/BlueButtonServer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/FhirServerConfig.java
Actually a lightly-hacked local/fake release of it that incorporates https://github.com/jamesagnew/hapi-fhir/pull/660.
http://issues.hhsdevcloud.us/browse/CBBD-262
(Be sure to see my note in that JIRA issue on how to build the version of HAPI you'll need for this.)
=> CBBD-262: Bumped to HAPI 2.4

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/BlueButtonStu3Server.java, bluebutton-server-app/src/main/resources/project.properties, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/ServerCapabilityStatementIT.java
http://issues.hhsdevcloud.us/browse/CBBF-63
=> CBBF-63 Customize and verify the server's CapabilityStatement

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/MedicareSegment.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/ServerCapabilityStatementIT.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageResourceProviderIT.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageTransformerTest.java
http://issues.hhsdevcloud.us/browse/CBBF-66
Once this and the other pending PRs are merged, I'll also need to:
* Update the other claim transformer code to properly reference `Coverage` resources.
* Update the `CapabilityStatement` tests to reflect `Coverage` support.
=> CBBF-66: Add Coverage support.

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProviderIT.java
http://issues.hhsdevcloud.us/browse/CBBF-64
=> CBBF-64: Patient search by logical ID

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformer.java
http://issues.hhsdevcloud.us/browse/CBBF-75
Unknown drug coverage status codes need to not blow things up.
=> CBBF-75: Fixed bug causing errors with random/dummy data

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ClaimType.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformer.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HHAClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerTestUtils.java
http://issues.hhsdevcloud.us/browse/CBBF-74
=> CBBF-74 EOB search that covers all claim types

bluebutton-server-app/src/main/config/server-config.sh, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java, bluebutton-server-app/src/main/resources/logback.xml
http://issues.hhsdevcloud.us/browse/CBBF-76
=> CBBF-76: ensure response timing/duration data is in access log

bluebutton-server-app/src/main/config/server-config.sh
http://issues.hhsdevcloud.us/browse/CBBF-77
This covers our local dev environments. Will push a similar change to the deployment scripts, which will cover the AWS environments and dev sandbox.
=> CBBF-77: Hardened the SSL/TLS config

bluebutton-server-app/src/main/config/server-config.sh, bluebutton-server-app/src/main/config/server-start.sh, bluebutton-server-app/src/main/config/server-stop.sh
Brian and I just missed these back in the first PR. The problems they cause don't show up on the "happy path", so they weren't caught by our tests, either.
https://issues.hhsdevcloud.us/browse/CBBF-100
=> CBBF-100: More script fixes

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformerTest.java, dev/api-changelog.md
1) Mapping FILL_NUM to an extension of item.quantity
2) Re-mapping DAYS_SUPPLY_NUM to an extension of item.quantity instead
of item.modifier
=> CBBF-128: Add FILL_NUM to PDE data

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HHAClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HospiceClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/InpatientClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SNFClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HHAClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HospiceClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/InpatientClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SNFClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerTestUtils.java, dev/api-changelog.md
1. Mapping FI_NUM to EOB.extension for Inp/Out/HHA/Hospice/SNF
2. Remvoing second occurrence of CCLTRNUM
3. Mapping SUPLRNUM to item.extension
4. Changing system and URL to point to DME_UNIT instead of MTUS_CNT
5. Changing system and URL to point to UNIT_IND instead of MTUS_IND
=> CBBF-110: FHIR Mapping Change (DME)

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HHAClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HospiceClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HHAClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HospiceClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerTestUtils.java, dev/api-changelog.md
- Mapping REV_UNIT for Outpatient, Hospice, and HHA
- Pointing System and URL for DME_UNIT/MTUS_IND in CarrierClaimn back to
MTUS_CNT/UNIT_IND (undoing change for Carrier in CBBF-110).
=> CBBF-109: FHIR Mapping Change (HHA)

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, dev/api-changelog.md
- REV_CNTR_PMT_AMT_AMT code value cahnged to read "Revenue Center
Payment Amount"
=> CBBF-108: FHIR Mapping Change (Hospice)

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformer.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformerTest.java, dev/api-changelog.md
- The field CARR_LINE_CLIA_LAB_NUM for Carrier was remapped as a
valueIdentifier from a valueCodeableConcept.
=> CBBF-135 Map Carrier CARR_LINE_CLIA_LAB_NUM

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformerTest.java, dev/api-changelog.md
- The field CARR_ANSTHSA_UNIT_CNT has been mapped to
item.service.extension only when the value is greater than zero.
=> CBBF-134 Map Carrier CARR_LINE_ANSTHSA_UNIT_CNT

.gitignore, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageTransformerTest.java, dev/api-changelog.md
Made changes for #2 and #3 in ticket [CBBF-123](https://issues.hhsdevcloud.us/browse/CBBF-123).  No changes for #1 at this time.
=> Cbbf 123 fhir mapping change (bene)

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/IcdCode.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CCWProcedureTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DiagnosisTest.java, dev/api-changelog.md
- Created test classes for CCWProcedure and Diagnosis to ensure they are
working properly. Each of these classes are extending IcdCode, so those
methods are tested as well.
=> CBBF-142: ICD codes have invalid Coding.system

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerTestUtils.java, dev/api-changelog.md
- new common method addExtensionValueQuantity
- new common method addExtensionValueIdentifier
- removed "if" check from several non-nullable fields
=> CBBF-146: Address FIXME's in Transformer-like classes

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HHAClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HospiceClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/InpatientClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SNFClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HHAClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HospiceClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SNFClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerTestUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtilsTest.java, dev/api-changelog.md
Just the one `Patient` field for now, but most all of the code that'll be needed to do this everwhere else is in place now.
https://issues.hhsdevcloud.us/browse/CBBF-140
=> CBBF-140: Proof-of-concept: include Coding.display values.

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HHAClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HospiceClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/InpatientClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SNFClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HHAClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HospiceClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/InpatientClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProviderIT.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SNFClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerTestUtils.java, dev/api-changelog.md
This is the big PR I've been threatening to drop for a while now -- finally done. I've been careful to keep each of the commits in here atomic and clean, so I strongly recommend reviewing it commit by commit, rather than all at once. The commit messages are sometimes a bit sparse, as the `api-changelog` changes included in most of the commits should thoroughly explain the goal(s) for each.
The _overall_ goal of this PR is to ensure that every URI returned by our API is a valid one that points to something useful (or potentially useful, at least -- I haven't created all of the needed static site pages yet).
I know it's big, but if you could review it ASAP, that would be **much** appreciated!
https://issues.hhsdevcloud.us/browse/CBBF-97
=> CBBF-97: Address remaining Extension/Coding/Identifier URIs

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/HospiceClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, dev/api-changelog.md
Trying to sneak in another API change before production usage starts. Thoughts?
https://issues.hhsdevcloud.us/browse/CBBF-169
=> CBBF-169: Fixed Money response codings

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java
set Observation.value even when hctHgbTestTypeCode is present and hctHgbTestResult is 0
=> cbbf-173 set Observation.value even when hctHgbTestTypeCode is present

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java
This is a bit hacky, but is the best solution I can think of at the moment: only log each failure 1x per `CcwCodeBookVariable`, per app launch. It'll still leave dupes across servers and restarts, but that
may actually be a good thing, as it may prompt us to actually care about the lookup failures. We'll see if it ends up being too annoying, I guess.
https://issues.hhsdevcloud.us/browse/CBBF-162
=> CBBF-162: Reduce log noise from codebook lookup failures

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java
Removed date search parameter code for all claim types.  Decided it was too hard to comment out the changes so I just removed the code.   
@karlmdavis    Can you pull this branch into your local machine, start the local server and run a curl command to pull back EOB data for a certain patient on your local database?   I can't get my local server to start.  Thanks.
=> removed date search parameter for all claim types

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProviderIT.java
Allows the Data Server to retrieve beneficiaries whose HICNs have changed, even when searching with an old HICN (provided that the CCW captured that old HICN).
https://jira.cms.gov/browse/BLUEBUTTON-185
=> BLUEBUTTON-185: Also search BeneficiaryHistory records for HICNs

dev/api-changelog.md
We hadn't captured the changes for these issues:
* CBBF-167
* BLUEBUTTON-185
* BLUEBUTTON-200
BLUEBUTTON-238
=> BLUEBUTTON-238: Update the change log to include recent work

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/BlueButtonServerInitializer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/ServerTestUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProviderIT.java, dev/api-changelog.md
Remove the old mapping as it has been replaced by "v1/fhir" and is no
longer needed to ensure compatibility.
=> BLUEBUTTON-306: Remove baseDstu3 mapping

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
Adding the total field (count of all entries in the system for that
patient) to the bundle.
=> BLUEBUTTON-604: Fix paging JSON response

bluebutton-server-app/src/test/resources/endpoint-responses/eobByPatientIdAll.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobByPatientIdPaged.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadCarrier.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadDme.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadOutpatient.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadPde.json
With the NPI changes brought in the golden files need to be updated to
reflect the changes in the endpoint response files.
=> BLUEBUTTON-814: Update endpoint response files for NPI changes

bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
Not the most elegant fix, admittedly. But gets the job done.
https://jira.cms.gov/browse/BLUEBUTTON-620
=> BLUEBUTTON-620: Fixed IT failures caused by new record type.

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PagingArguments.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java, bluebutton-server-app/src/test/resources/endpoint-responses/eobByPatientIdPaged.json
Cherry picking changes from BLUEBUTTON-765-Changes-to-EOB-paging
=> Bluebutton 765 re changes to eob paging

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PagingArguments.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProviderIT.java, bluebutton-server-app/src/test/resources/endpoint-responses/metadata.json
- Adding paging to the Patient resource provider as described in the
FHIR spec (see https://www.hl7.org/fhir/search.html ).
- Moved link creation/adding to the bundle into the PagingArguments
class
=> BLUEBUTTON-767: Add paging to the Patient resource

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageTransformer.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CoverageResourceProviderIT.java, bluebutton-server-app/src/test/resources/endpoint-responses/metadata.json
Adding paging to the Coverage resource as described in the FHIR spec
(see https://www.hl7.org/fhir/search.html ).
=> BLUEBUTTON-766: Add paging to the Coverage resource

bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/utils/EndpointJsonResponseComparatorIT.java, bluebutton-server-app/src/test/resources/endpoint-responses/coverageRead.json, bluebutton-server-app/src/test/resources/endpoint-responses/coverageSearchByPatientId.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobByPatientIdAll.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobByPatientIdPaged.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadCarrier.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadDme.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadHha.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadHospice.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadInpatient.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadOutpatient.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadPde.json, bluebutton-server-app/src/test/resources/endpoint-responses/eobReadSnf.json, bluebutton-server-app/src/test/resources/endpoint-responses/metadata.json, bluebutton-server-app/src/test/resources/endpoint-responses/patientByIdentifier.json, bluebutton-server-app/src/test/resources/endpoint-responses/patientRead.json, bluebutton-server-app/src/test/resources/endpoint-responses/patientSearchById.json
First step, changes to the IT for a place to get a handle on the JSON
fields that will need to be updated. This in turn slightly changes the
format of all golden files. Committing them now so that in subsequent
commits we can look specifically at the fields that are being replaced.
=> BLUEBUTTON-802: Replace ignored fields with filler text

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/Sex.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/utils/EndpointJsonResponseComparatorIT.java
Changing to check the sex field for the correct values of 0/1/2 (as the
data is stored in our database) versus M/F.
BLUEBUTTON-898
=> Updating to check for correct sex value characters

dev/api-changelog.md
=> Update our api-changelog for the sex field changes to BeneficiaryTransformer

dev/api-changelog.md
This commit just got missed in the earlier PR, so adding it separately here.
BLUEBUTTON-926
=> More details in API changelog for new fields

bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/utils/EndpointJsonResponseComparatorIT.java
Was not specifying that they be written out as UTF-8.
BLUEBUTTON-926
=> BLUEBUTTON-926: Fixing the character encoding of the golden files.

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SNFClaimTransformer.java
Fixing our code to account for missing data for diagnosis admitting code
in the SNFClaimTransformer.
=> BLUEBUTTON-1061: Fixing NoSuchElementException PROD error

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformer.java
Instead of throwing an exception when our data has a gender value other than 0,1, or 2, I changed it to log a warning of the data issue and populate our response with the UNKNOWN gender value. 
BLUEBUTTON-1095
=> Change thrown exception to warning and use default value

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java
It was failing for bad data, which means it failed for just about every record in our TEST environment.
https://jira.cms.gov/browse/BLUEBUTTON-1033
=> BLUEBUTTON-1033: Fixed a bug in the FDA drug lookup

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java
This is Round 3 for the changes from this earlier (reverted) PR: https://github.com/CMSgov/bluebutton-data-server/pull/143. Basically, we're adding an option to include plaintext HICNs and MBIs in the `Patient.identifier` results.
Originally, the PR was reverted as it needed a DB index that wasn't present. That index was added in https://github.com/CMSgov/bluebutton-data-model/pull/77, and so this enhancement should now be safe to deploy.
The "round 2" attempt from this PR also failed in PROD: https://github.com/CMSgov/bluebutton-data-server/pull/157. It turns out that in order to properly respond to the query used there, the DB had to first `LEFT JOIN` all rows in `BeneficiariesHistory` to all rows in `Beneficiaries`, which takes forever. We avoid that problem here by manually doing that …
=> BLUEBUTTON-865: return plaintext HICNs and MBIs for BCDA (round 3)

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java
=> Add JPA timeout

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java
I think this hangs up the database connection but it doesn't return a response to the client.
=> Undo timeout for now

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java
=> Add timeout back for testing

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java
=> Backout change so Karl's can go through.

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderTest.java, bluebutton-server-app/src/test/resources/endpoint-responses/metadata.json, dev/api-changelog.md
See the `api-changelog.md` changes for details.
https://jira.cms.gov/browse/BLUEBUTTON-1191
=> BLUEBUTTON-1191: Add support for filtering EOB results by type

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java
=> Use different JPA config setting

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java
=> Set sequential scan to on for test.

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java
=> Set timeout to 30
