CMSgov/bluebutton-data-server

bbonfhir-server-app/src/main/config/server-config-healthapt.sh
Just a couple of small tweaks in here that are required by the benchmarks for [CBBD-119: Create ETL performance tests](http://issues.hhsdevcloud.us/browse/CBBD-119).
The interface change in here must have been done by someone manually in the HealthAPT environments.
=> CBBD-119: Config tweaks needed in benchmarks

bbonfhir-server-app/src/main/config/server-start.sh
Somewhat related to CBBD-138, as it was annoying me while I worked on it, but mostly just an unrelated bug that needed to be stomped. Should prevent us from having to restart build server every time an IT fails.
=> Fixed bug in server-start.sh, where it called wrong -stop.sh on error.

.gitignore, bbonfhir-server-app/src/main/config/server-config-healthapt.sh, bbonfhir-server-app/src/main/config/server-config.sh, bbonfhir-server-app/src/main/config/server-stop.sh
This seems to have been the root cause of [CBBD-141: Intermittent benchmark failure due to JBoss/Wildfly connect timeouts](http://issues.hhsdevcloud.us/browse/CBBD-141), and isn't a bad idea, regardless.
=> CBBD-141: Increase Wildfly connect timeouts

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/FhirServerConfig.java
http://issues.hhsdevcloud.us/browse/CBBF-39
See my commit message for an explanation.
=> CBBF-39: Actually remove Lucene indexes from HAPI FHIR server (for reals this time)

bluebutton-server-app/src/main/config/server-config-healthapt.sh, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/FhirServerConfig.java
The previous/default approach of calculating a value based on the number
of processors is okay, but doesn't really allow for multi-system
environments where the FHIR server has less/more CPUs than the ETL
server.
=> CBBD-248: Make the number of server DB connections configurable

bluebutton-server-app/src/main/config/server-config-healthapt.sh
Removing a broken (and unneeded) if clause.
This was preventing the script from correctly configuring the server to
listen on all IPs. Instead, it was only listening on the loopback
address.
http://issues.hhsdevcloud.us/browse/CBBF-59
=> CBBF-59: Server config script not configuring servers to listen on all IPs

bluebutton-server-app/src/main/resources/logback.xml
Every create operation now runs a search (thanks to our `If-None-Exists` usage), and every one of those gets logged.
It doesn't appear to be slowing down the FHIR server any, but it will eventually eat a ton of disk space. And it makes the logs almost useless -- can't find anything else in there with all of the noise.
http://issues.hhsdevcloud.us/browse/CBBF-60
=> CBBF-60: Dialing down the log spamming from ETL

bluebutton-server-app/src/main/config/server-config.sh
This change covers our local dev environments.
For some unknown reason, the two removed ciphers are supported in our dev sandbox, but not in the HealthAPT dev/test/prod environments. I assume it has something to do with JBoss EAP 7.0 (as the sandbox uses Wildfly, instead), but it could also be a problem with how Java is installed/configured.
Since we can live without the two ciphers, they're just disabled. And even though the ciphers work in our local dev environments, we disable them there to maintain consistency with the other environments.
=> CBBF-77: Disabled the ChaCha20 ciphers

bluebutton-server-app/src/main/config/server-config.sh
These headers will probably not ever appear, as our ITs don't set them. However, per CBBP-603, the frontend is now setting them. Really, I'm just updating them here to ensure that the local dev access logs' format matches the format that will appear in the dev/test/prod/dpr environments.
Note: Wildfly will drop "-" characters into the access log for these fields, when the headers aren't actually present.
https://issues.hhsdevcloud.us/browse/CBBF-103
=> Set access log to include request header metadata

Jenkinsfile, bluebutton-server-app/pom.xml, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/ServerTestUtils.java, bluebutton-server-app/src/test/resources/logback-test.xml
Some functional changes here:
* For now, run `mvn install` instead of `mvn deploy`. Will switch if/when a Nexus server is available.
* Only change versions for non-master builds.
* Archive the things that matter, but not binaries, as that's a duplicate waste of space. Do fingerprint binaries, though.
https://issues.hhsdevcloud.us/browse/CBBI-289
=> CBBI-289: Updated the Jenkinsfile for new Jenkins server.

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerTestUtils.java, dev/api-changelog.md
I merged the master in.  One change of note from master is the providerBillingNumber was mapped as a CodeableConcept but is now mapped as an extension identifier string at the item level in the eob.
=> Cbbf 126 provider number is not mapped for the dme claim type at the eob level

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/IcdCode.java
- Changes to IcdCode.getFhirSystem() to compare icdVersionCode (char
type) to a character value (versus a string)
=> CBBF-142: ICD Codes have invalid Coding.system

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CCWProcedureTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CarrierClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DMEClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/DiagnosisTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/InpatientClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/OutpatientClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PartDEventTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/SNFClaimTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerTestUtils.java
This flattens the json output from a query.  Specifically uses Option 4 as described here [Extension Design](https://confluence.cms.gov/pages/viewpage.action?spaceKey=BB&title=Extension+Design)
=> Cbbf 127 modify fhir extension design

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CCWProcedure.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/CCWProcedureTest.java
Enhanced code to allow for optional procedure date when procedure code is present.  Procedure date was assumed to be present when procedure code was also present before; now the date isn't required.
=> cbbf-171 enhance code to allow for optional procedure date

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/SpringConfiguration.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
Switched to a workaround that allows us to leave all subqueries enabled. It's still gross, but definitely an improvement.
(Work continues to try and determine the actual root cause. Right now it's looking like Postgres is sad that it doesn't have more memory to keep the indexes hot.)
https://issues.hhsdevcloud.us/browse/CBBI-357
=> CBBI-357: Slow DB Queries Bandaid #2

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/Diagnosis.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, dev/api-changelog.md
The previous code had a bug where all values were concat'd into a single Coding.code value of the form "[CODE1, CODE2]".
This is definitely a backwards-incompatible change, but I believe it's warranted given that:
1. There still aren't any production users of the API.
2. The current format is clearly a bug and invalid.
3. It's a minor enough change that it likely won't impact many applications.
As an aside, I think I'd still push for fixing it now, even if we already had production users.
https://issues.hhsdevcloud.us/browse/CBBF-175
=> Fixed EOB.diagnosis.type.

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ClaimType.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProvider.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
Fixed the bug in https://jira.cms.gov/browse/BLUEBUTTON-200. This is/was caused by a pretty surprising (to me, at least) JPA problem, where non-lazy-load queries across multiple entities (e.g. an `INNER JOIN` like we're doing here) cause duplicate top-level entities to be returned by JPA: one for each of the result set rows. In this specific case, we were getting a `FooClaim` instance for every `FooClaimLine` row that was found. This is often referred to as the "N+1" problem with JPA, for reasons that escape me.
While I was in there, I also cleaned up the related code quite a bit, as it'd started to get out of hand.
=> BLUEBUTTON-200: Fix duplicate EOBs bug

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/BlueButtonServerInitializer.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/ServerTestUtils.java, bluebutton-server-app/src/test/resources/logback-test.xml
Changing the path mapping from /baseDstu3/ to /v1/fhir/ so that the frontend does not need to replace the URL values in the fhir response we are sending to them.
=> BLUEBUTTON-130: Create reference links and response based on base path

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformer.java, dev/api-changelog.md
Reverts CMSgov/bluebutton-data-server#104
@dho937 Apologies, but reverting since that earlier change never got the product management signoff it needed.
And thinking about it some more, I think it's ultimately not as big a deal, anymore. Happy to discuss why offline.
=> Revert "BLUEBUTTON-239: Remove HICN hash from returned EOBs"

bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerTestUtils.java, dev/api-changelog.md
Looks like https://github.com/CMSgov/bluebutton-data-server/pull/116 was erroneously reported as passing the build: it wasn't. I think it's just a build ordering issue: that build completed before the sample data change that it relied on was merged to `master`.
https://jira.cms.gov/browse/BLUEBUTTON-507
=> BLUEBUTTON-480: Fix test failure and update change log

bluebutton-server-app/src/main/config/server-start.sh, bluebutton-server-app/src/main/config/standalone.xml, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/LoggingContextFilter.java, bluebutton-server-app/src/main/webapp/WEB-INF/jboss-web.xml, bluebutton-server-app/src/main/webapp/WEB-INF/web.xml, dev/ssl-stores/server-roles.properties
Main change here is the addition of the `<security-domain name="bluebutton-data-server" />` configuration entry, and the `jboss-web.xml` file that activates/selects it for this app. Most everything else just supports that switch.
How does this result in client SSL principals being logged? It makes the "`%r`" variable in our access log pattern (in `standalone.xml`) actually work. With the security domain configured this way, to read the client certificate, the remote use is available and captured in our access logs, e.g. (note the "`CN=client-local-dev`"):
127.0.0.1 - CN=client-local-dev 29/Jun/2019:21:56:38 -0400 "GET /v1/fhir/metadata HTTP/1.1" "?-" 200 -1 2 - - [-] - "-" - "-" - "-" -
Note the companion PR for `ansible-role-bluebutton-data-server` that has already been merged and …
=> BLUEBUTTON-945: Log client SSL principals in access.log

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExtraParamsInterceptor.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProviderIT.java, bluebutton-server-app/src/test/resources/endpoint-responses/metadata.json, dev/api-changelog.md
Adding two additional identifiers to the patient resource when querying
for BCDA users (includeIdentifiers=true).
BLUEBUTTON-865
=> BLUEBUTTON-865: Adding plaintext HICN and MBI to patient resource

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformer.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerConstants.java, bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/TransformerUtils.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/BeneficiaryTransformerTest.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/ExtraParamsInterceptor.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProviderIT.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/utils/EndpointJsonResponseComparatorIT.java, bluebutton-server-app/src/test/resources/endpoint-responses/patientByIdentifier.json, bluebutton-server-app/src/test/resources/endpoint-responses/patientByIdentifierWithIncludeIdentifiers.json, bluebutton-server-app/src/test/resources/endpoint-responses/patientRead.json, bluebutton-server-app/src/test/resources/endpoint-responses/patientReadWithIncludeIdentifiers.json, bluebutton-server-app/src/test/resources/endpoint-responses/patientSearchById.json, bluebutton-server-app/src/test/resources/endpoint-responses/patientSearchByIdWithIncludeIdentifiers.json, dev/api-changelog.md
This is Round 2 for the changes from this earlier (reverted) PR: https://github.com/CMSgov/bluebutton-data-server/pull/143. Basically, we're adding an option to include plaintext HICNs and MBIs in the `Patient.identifier` results.
Originally, the PR was reverted as it needed a DB index that wasn't present. That index was added in https://github.com/CMSgov/bluebutton-data-model/pull/77, and so this enhancement should now be safe to deploy.
This PR is a revert-of-the-revert, with some additional tweaks:
* Improve performance a bit by going from 3 DB queries down to 1.
* Try harder to not send plaintext HICNs and MBIs to the transformer, when they're not needed.
* Tweak the API changelog a bit.
* Added `EndpointJsonResponseComparatorIT` test cases to cover the new query types. …
=> BLUEBUTTON-865: return plaintext HICNs and MBIs for BCDA (Round 2)

bluebutton-server-app/src/main/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProvider.java, bluebutton-server-app/src/test/java/gov/hhs/cms/bluebutton/server/app/stu3/providers/PatientResourceProviderIT.java
The default `JoinType` for `fetch(...)` is `INNER`, which causes lookups to fail for any benes that don't have historical ID records -- only when IncludeIdentifiers is enabled.
https://jira.cms.gov/browse/BLUEBUTTON-865
=> BLUEBUTTON-865: Fix IncludeIdentifiers bug causing failed searches
